# Generated by Django 3.2.9 on 2021-11-29 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('video_source', models.URLField(verbose_name='Video ')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Running', 'Running')], default='Running', max_length=10, verbose_name='Status')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('use_dash', models.BooleanField(default=False, verbose_name='Use Dash')),
                ('dash_file', models.URLField(blank=True, help_text='This field will be auto generated', null=True, verbose_name='Dash file')),
                ('use_hls', models.BooleanField(default=False, verbose_name='Use HLS')),
                ('hls_file', models.URLField(blank=True, help_text='This field will be auto generated', null=True, verbose_name='HLS file')),
                ('duration', models.FloatField(default=0, help_text='This field will be auto generated', verbose_name='Duration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
