
version: "3.0"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "walnut"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"